print("=+=+=+=+= Data Diri Mahasiswa =+=+=+=+=")
nim = input("NIM : ")
nama = input("Nama Lengkap : ")
jurusan = input("Jurusan : ")
alamat = input("Alamat : ")

print("Hasil cetak data di atas adalah")
print("NIM : " +str(nim))
print("Nama : " +str(nama))
print("Jurusan : " +str(jurusan))
print("Alamat : " +str(alamat))