nim = input("Masukkan NIM Anda : ")
nama = input("Masukkan Nama Anda : ")
n1 = int(input("Masukkan Nilai Tugas 1 : " ))
n2 = int(input("Masukkan Nilai Tugas 2 : " ))
print("Universitas Bina Sarana Informatika")
print("----------------------------------")
print("NIM Anda adalah : " + str(nim))
print("Nama Anda adalah : " +str(nama))
print("Nilai Tugas 1 Anda adalah : " +str(n1))
print("Nilai Tugas 2 Anda adalah : " +str(n2))
print("Nilai total tugas Anda adalah : " +str((n1+n2)/2))